Hw6
VOVASTAR/Java_Pro_Hillel_01_02_24 pull request #5
Opened 2024-02-17 22:59 UTC by VOVASTAR

2024-02-23 17:15 UTC, pipekalo requested changes

2024-02-23 17:15 UTC, pipekalo commented on src/homework/hw6/competition/obstruction/Treadmill.java
> +            participant.setFinishCompetition(false);
ты можешь ставить тут true а там где проверяешь этот флаг убрать отрицание, упростить тем самым. Естественно перемименуй переменную в что то типо "ПровалилЛиПолосуПрепятствии"

2024-02-23 22:28 UTC, VOVASTAR commented on src/homework/hw6/competition/obstruction/Treadmill.java
> +            participant.setFinishCompetition(false);
изменил

2024-02-26 15:32 UTC, pipekalo approved these changes

2024-02-27 21:43 UTC, merged